# Generated by Django 5.2.17 on 2026-08-25 13:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Empdetails', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='details',
            new_name='Employee',
        ),
    ]
